[package]
name = "cmus-discord-rich-presence"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-rich-presence = "0.2.5"
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
